staging-settings:
  user-workflow:
    workflow-name: "uat-nav-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: ""

production-settings:
  user-workflow:
    workflow-name: "uat-nav-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: ""
